# server port
server:
  port: 80

# spring
spring:
  # zipkin
  zipkin:
    baseUrl: http://zipkin:9411

  # database
  datasource:
    url: jdbc:mysql://adventuresmysql:3306/adventures
    username: adventures
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

# registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://edgeregistry/eureka/
  instance:
    prefer-ip-address: true
