# server port
server:
  port: 80

spring:
  # zipkin
  zipkin:
    baseUrl: http://zipkin:9411

  # database
  datasource:
    url: jdbc:mysql://reservationsmysql:3306/reservations
    username: reservations
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

  # access
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/wild-adventures

# registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://edgeregistry/eureka/
  instance:
    prefer-ip-address: true

wildadventures:
  reservations:
    # stripe
    stripe:
      apiKey: sk_test_d4kkzu8uQI9Eq6Hjd7lCqkvu00xJqY4s9r

    # business rules
    business:
      reservationLimitDays: 4
